var app = new Vue({
  el: '#app',
  data: {
    message: 'Hello World!',
    fromType: 'USD',
    fromAmount: 0,
    toType: 'EUR',
    toAmount: 0,
    errorMessage: '',
    loading: false,
    options: [
      { code: "AED" },
      { code: "AFN" },
      { code: "ALL" },
      { code: "AMD" },
      { code: "ANG" },
      { code: "AOA" },
      { code: "ARS" },
      { code: "AUD" },
      { code: "AWG" },
      { code: "AZN" },
      { code: "BAM" },
      { code: "BBD" },
      { code: "BDT" },
      { code: "BGN" },
      { code: "BHD" },
      { code: "BIF" },
      { code: "BMD" },
      { code: "BND" },
      { code: "BOB" },
      { code: "BRL" },
      { code: "BSD" },
      { code: "BTC" },
      { code: "BTN" },
      { code: "BWP" },
      { code: "BYN" },
      { code: "BYR" },
      { code: "BZD" },
      { code: "CAD" },
      { code: "CDF" },
      { code: "CHF" },
      { code: "CLF" },
      { code: "CLP" },
      { code: "CNY" },
      { code: "COP" },
      { code: "CRC" },
      { code: "CUC" },
      { code: "CUP" },
      { code: "CVE" },
      { code: "CZK" },
      { code: "DJF" },
      { code: "DKK" },
      { code: "DOP" },
      { code: "DZD" },
      { code: "EGP" },
      { code: "ERN" },
      { code: "ETB" },
      { code: "EUR" },
      { code: "FJD" },
      { code: "FKP" },
      { code: "GBP" },
      { code: "GEL" },
      { code: "GGP" },
      { code: "GHS" },
      { code: "GIP" },
      { code: "GMD" },
      { code: "GNF" },
      { code: "GTQ" },
      { code: "GYD" },
      { code: "HKD" },
      { code: "HNL" },
      { code: "HRK" },
      { code: "HTG" },
      { code: "HUF" },
      { code: "IDR" },
      { code: "ILS" },
      { code: "IMP" },
      { code: "INR" },
      { code: "IQD" },
      { code: "IRR" },
      { code: "ISK" },
      { code: "JEP" },
      { code: "JMD" },
      { code: "JOD" },
      { code: "JPY" },
      { code: "KES" },
      { code: "KGS" },
      { code: "KHR" },
      { code: "KMF" },
      { code: "KPW" },
      { code: "KRW" },
      { code: "KWD" },
      { code: "KYD" },
      { code: "KZT" },
      { code: "LAK" },
      { code: "LBP" },
      { code: "LKR" },
      { code: "LRD" },
      { code: "LSL" },
      { code: "LTL" },
      { code: "LVL" },
      { code: "LYD" },
      { code: "MAD" },
      { code: "MDL" },
      { code: "MGA" },
      { code: "MKD" },
      { code: "MMK" },
      { code: "MNT" },
      { code: "MOP" },
      { code: "MRO" },
      { code: "MUR" },
      { code: "MVR" },
      { code: "MWK" },
      { code: "MXN" },
      { code: "MYR" },
      { code: "MZN" },
      { code: "NAD" },
      { code: "NGN" },
      { code: "NIO" },
      { code: "NOK" },
      { code: "NPR" },
      { code: "NZD" },
      { code: "OMR" },
      { code: "PAB" },
      { code: "PEN" },
      { code: "PGK" },
      { code: "PHP" },
      { code: "PKR" },
      { code: "PLN" },
      { code: "PYG" },
      { code: "QAR" },
      { code: "RON" },
      { code: "RSD" },
      { code: "RUB" },
      { code: "RWF" },
      { code: "SAR" },
      { code: "SBD" },
      { code: "SCR" },
      { code: "SDG" },
      { code: "SEK" },
      { code: "SGD" },
      { code: "SHP" },
      { code: "SLL" },
      { code: "SOS" },
      { code: "SRD" },
      { code: "STD" },
      { code: "SVC" },
      { code: "SYP" },
      { code: "SZL" },
      { code: "THB" },
      { code: "TJS" },
      { code: "TMT" },
      { code: "TND" },
      { code: "TOP" },
      { code: "TRY" },
      { code: "TTD" },
      { code: "TWD" },
      { code: "TZS" },
      { code: "UAH" },
      { code: "UGX" },
      { code: "USD" },
      { code: "UYU" },
      { code: "UZS" },
      { code: "VEF" },
      { code: "VND" },
      { code: "VUV" },
      { code: "WST" },
      { code: "XAF" },
      { code: "XAG" },
      { code: "XAU" },
      { code: "XCD" },
      { code: "XDR" },
      { code: "XOF" },
      { code: "XPF" },
      { code: "YER" },
      { code: "ZAR" },
      { code: "ZMK" },
      { code: "ZMW" },
      { code: "ZWL" }
    ]
  },
  methods: {
    selectTo: function(event) {
      this.toType = event.target.innerText;
    },
    selectFrom: function(event) {
      this.fromType = event.target.innerText;
    },
    convert: function(event) {
      this.loading = true;
      fetch(`${base_url}?access_key=${access_key}&format=1`)
        .then(response => response.json())
        .then(json => {
          if (json.success) {
            var euros = (this.fromType === "EUR") ? this.fromAmount : this.fromAmount/json.rates[this.fromType];
            console.log(this.fromType, "to EUR", euros);
            var amount = euros * json.rates[this.toType];
            console.log("EUR to", this.toType, amount);
            this.toAmount = amount;
          }
          else {
            this.errorMessage = json.error.info;
          }
          this.loading = false;
        })
    }
  }
})


const base_url = 'http://data.fixer.io/api/latest';
const access_key = '02c421fa81a751f119aac818f4062b1f';
